bug: Correcting URLs on https://rubygems.org/gems/forem_lite
andrewmcodes/forem_lite pull request #3
Opened 2020-07-29 21:20 UTC by MikeRogers0

## What is the purpose of this pull request?

Fixes the metadata links on https://rubygems.org/gems/forem_lite

![image](https://user-images.githubusercontent.com/325384/88854644-82302580-d1e9-11ea-9dc4-8ba22d8e6762.png)

## What changes did you make? (overview)

Right now they're linking to `https://github.com/andrewmcodes/forem_lite/forem_lite` instead of `https://github.com/andrewmcodes/forem_lite`. So updated the references in the gemspec.

## Is there anything you'd like reviewers to focus on?

## Checklist

- [ ] I've added tests for this change
- [ ] I've added a Changelog entry
- [ ] I've updated a documentation

If you liked this PR, please consider [buying me a coffee](https://www.buymeacoffee.com/MikeRogers0) ☕️

2020-07-31 17:50 UTC, andrewmcodes requested changes
Lol thanks for catching this. One small request!

2020-07-31 17:50 UTC, andrewmcodes commented on forem_lite.gemspec
> +    "source_code_uri" => s.homepage.to_s
No need for `.to_s` on these.

2020-08-01 18:45 UTC, MikeRogers0 commented on forem_lite.gemspec
> +    "source_code_uri" => s.homepage.to_s
@andrewmcodes Sorted :D

2020-08-21 22:32 UTC, andrewmcodes approved these changes
Thank you!

2020-08-21 22:32 UTC, merged